---
apiVersion: v1
kind: Secret
metadata:
  name: test2-poi-map-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rhdh-xchange/test2-frontend-gitops
